---
title: "Progress Memo 1"
subtitle: |
  | Final Project 
  | Data Science 1 with R (STAT 301-1)
author: "Karthik Sathish"
date: today

format:
  html:
    toc: true
    embed-resources: true
    
execute:
  echo: false
  warning: false

from: markdown+emoji 
---



::: {.callout-tip icon=false}

## Github Repo Link


[My Github Repo Link](https://github.com/stat301-1-2023-fall/final-project-1-kvsathish)

:::


## Data source


The source of my data is a user on `Kaggle.com`, named Xavier. Their username is `xvivancos`, and they are a data science enthusiast that are also a Kaggle Grandmaster. Their roots are from Barcelona and Catalonia, Spain. The dataset is named `Michael Jordan, Kobe Bryant and Lebron James stats`^[Found on https://www.kaggle.com/datasets/xvivancos/michael-jordan-kobe-bryant-and-lebron-james-stats/data?select=per_game_stats.csv]. Although all the stats were compiled by Xavier, the raw statistical data is from Basketball Reference^[Found on https://www.basketball-reference.com/].

As of right now, I plan on utilizing a singular dataset called `allgames_stats` to compare the every game statistics between Lebron James, Michael Jordan, and Kobe Bryant. However, if I feel as though there is not enough observations or variable provided, I may dive into the `advanced_stats`, `allstar_games_stats`, `game_high_stats`, and `totals_stats` to combine information and analyze the data more holistically. If I need to join these datasets together, I plan on aligning variables based on similarity and function. I think I will be able to combine the data seamlessly if need be.


## Why this data

I chose this dataset because I have thought long and hard about who the greatest basketball player of all time is. This question is somewhat subjective based on your individual meaning of "great." Not only have I looked into a range of factors that contribute to being the greatest, I've also had countless debates with other people about who the GOAT of basketball is. Instead of simply pointing to the number of championships a player has won, I wanted to look into the statistics of all games played by Lebron James, Michael Jordan, and Kobe Bryant to justify who the best player is at the core of the game. I know that longevity of a player's career and injuries may influence the data, but I plan to account for any confounding variables based on my ball knowledge and further thorough research. 

Personally, I have been one of the biggest Lebron James fans my whole life, but I plan to put biases aside to let the numbers decide who the greatest player of all time is. I understand that Michael Jordan and Kobe Bryant have culturally changed the game, and I would like to simplify argument for the greatest player of all time to the raw statistics provided by the dataset.


## Data quality & complexity check

#### Loading and reading in data 

library(tidyverse)

allgames_stats <- read_csv("data/allgames_stats.csv")

#### Analyzing the data

In the dataset, there are 29 total variables and 4,254 total observations. Moreover, there are 6 categorical variables as well as 23 numerical variables. In terms of missingness, there is an issue for home games vs. away games. In this dataset, home games are represented with `NA` values for the `X` variable. Also, some of the statistical percentages reflect `NA` values because zero attempts were made. I plan to account for these `NA` values on top of games missed due to injury during my final reflection of the dataset in my EDA.


## Potential data issues

Some potential issues that may arise include cleaning the data of missing values, evaluating context for some statistics, and possibly merging the advanced player statistics in my final EDA. To clean the data of missing values, I plan to take out observations that are indicative of games the player missed due to injury or extenuating circumstances. By context, I mean properly evaluating the primes of player careers as well as accounting for the age of a player during certain seasons. In terms of the advanced statistics, I plan on utilizing advanced statistics to further prove or disprove certain trends seen in the initial analysis. Finally, it is important to understand how the game has actually changed over time, whether it be the importance of the three point line, spacing, or defensive intensity.

## Misc

#### Goal: Finish the project by Wednesday, November 29th.

#### Timeline:

Week 1 - Figure out how to attack the central question (Which player is the greatest of all time?).

Week 2 - Plan out the EDA, tidy the data, and begin creating graphics to serve as evidence in answering the central question.

Week 3 - Finish building all the necessary graphics needed for proper analysis of the data. Decide whether advanced stats should be incorporated in the final EDA.

Week 4 - Write up all the analysis and make sure to weigh the context behind all the final statistics for effective conclusions.
